// Run this script with `ts-node ./bitfinexAssetScript.ts
import {writeFileSync} from 'fs';
import {join} from 'path';

const fetch = require('node-fetch');


fetch('https://api-pub.bitfinex.com/v2/conf/pub:map:currency:sym')
	.then( res => res.json())
	.then( list => {
		const toBFX = {};
		const toLocal = {};
		
		list[0].forEach( pair => {
			if( !pair[0].endsWith('F0') ){
				console.log( 'pair', pair );
				let localName = pair[1].toUpperCase();
				toBFX[localName] = pair[0];
				toLocal[pair[0]] = localName;
			}
		})

		const content = `
// This file is autogenerated by bitfinexAssetsScript.ts
export const assetToBtf = ${JSON.stringify(toBFX, null, 2)};
export const assetToLocal = ${JSON.stringify(toLocal, null, 2)};
		`
		const path = join(__dirname, './bitfinexAssetTranslations.ts');
		writeFileSync(path, content, 'utf-8');
	})
;